#- name: Install dependent apt packages
#  become: true
#  apt:
#    state: present
#    name:
#    - python3-pip

#- name: Install dependent pip packages
#  become: true
#  pip:
#    name:
#    - pyyaml

- name: Ensure zigbee2mqtt app directory exists
  file:
    path: /var/zigbee2mqtt
    state: directory
    mode: '0755'
- name: Ensure zigbee2mqtt data directory exists
  file:
    path: /var/zigbee2mqtt/data
    state: directory
    mode: '0755'
- name: Copy configuration.yaml
  copy:
    src: configuration.yaml
    dest: /var/zigbee2mqtt/data/configuration.yaml
  register: zigbee2mqtt_config
- name: Create secrets.yaml
  template:
    src: secrets.yaml.j2
    dest: /var/zigbee2mqtt/data/secrets.yaml
- name: Run zigbee2mqtt via docker-compose
  community.docker.docker_compose_v2:
    project_name: zigbee2mqtt
    state: "{{ 'restarted' if zigbee2mqtt_config.changed else 'present' }}"
    definition:
      services:
        zigbee2mqtt:
          container_name: zigbee2mqtt
          image: koenkk/zigbee2mqtt:latest-dev@sha256:ce893fa426dd6af05cd28088d8283277673469d26523d824929d5ed13b94755d
          restart: unless-stopped
          volumes:
          - /var/zigbee2mqtt/data:/app/data
          - /run/udev:/run/udev:ro
          ports:
          - 8080:8080
          environment:
          - TZ=Europe/London
          devices:
          - /dev/ttyUSB0:/dev/ttyACM0
