- name: Ensure /mnt/data/uptime-kuma exists
  file:
    path: /mnt/data/uptime-kuma
    state: directory
    owner: root
    group: root
    mode: '0700'
- name: Run uptime kuma via docker-compose
  community.docker.docker_compose_v2:
    project_name: uptime_kuma
    definition:
      services:
        uptime_kuma:
          image: louislam/uptime-kuma:1.23.13
          network_mode: host
          volumes:
          - /mnt/data/uptime-kuma:/app/data
          restart: unless-stopped
