apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: default
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: default
  connection:
    bufferLimit: 4G
