apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: default
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: default
  tls:
    alpnProtocols: [http/1.0, http/1.1]
