apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tk831-media-applications
spec:
  goTemplate: true
  generators:
  - git:
      repoURL: https://gitea.tk831.net/Ops/media-app-of-apps.git
      revision: HEAD
      directories:
      - path: by-cluster/red-squadron/applications/by-namespace/*/*
  template:
    metadata:
      name: 'tk831-media-{{.path.basename}}'
    spec:
      project: tk831
      source:
        repoURL: https://gitea.tk831.net/Ops/media-app-of-apps.git
        targetRevision: HEAD
        path: '{{.path.path}}'
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{index .path.segments 4}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
          allowEmpty: false
