- name: Ensure restic data directory exists
  become: true
  ansible.builtin.file:
    path: /var/mnt/backup/data/restic
    state: directory
    owner: root
    group: rclone
    mode: '0770'
- name: Create .htpasswd file
  become: true
  community.general.htpasswd:
    path: /var/mnt/backup/data/restic/.htpasswd
    name: "{{ (lookup('community.hashi_vault.vault_kv2_get', 'system/data-backup-server/restic_credentials', url=vault_address, engine_mount_point=vault_secret_mount)).secret.username }}"
    password: "{{ (lookup('community.hashi_vault.vault_kv2_get', 'system/data-backup-server/restic_credentials', url=vault_address, engine_mount_point=vault_secret_mount)).secret.password }}"
    hash_scheme: sha256_crypt
    owner: root
    group: rclone
    mode: '0640'
- name: Create rclone-restic-server quadlet
  become: true
  containers.podman.podman_container:
    name: rclone-restic-server
    state: quadlet
    image: docker.io/restic/rest-server:0.14.0
    user: "0:0"
    uidmap: ["0:2000"]
    gidmap: ["0:2500"]
    volume:
    - /var/mnt/backup/data/restic:/data:z
    ports:
    - "8080:8000"
    quadlet_options:
    - |
      Environment=OPTIONS="--prometheus-no-auth --group-accessible-repos"

      [Unit]
      RequiresMountsFor=/var/mnt/backup/data

      [Service]
      Restart=on-failure
      RestartSec=5s

      [Install]
      WantedBy=default.target
  register: container_definition
- name: systemd daemon-reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
- name: (Re)start rclone server service
  become: true
  ansible.builtin.systemd:
    name: rclone-restic-server
    enabled: true
    state: "{{ 'restarted' if container_definition.changed else 'started' }}"
