apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.14.11
- ./resources/routes.yaml
- ./resources/keycloak-credentials.yaml
# Repository Credentials
- ./resources/repository-credentials/wtaylor-gitea-credentials.yaml
- ./resources/repository-credentials/wtaylor-gitea-credentials-old.yaml
- ./resources/repository-credentials/wtaylor-github-credentials.yaml
# Repositories
- ./resources/repositories/gitea-ops-repositories.yaml
- ./resources/repositories/gitea-wtaylor-repositories.yaml
- ./resources/repositories/gitea-ops-repositories-old.yaml
- ./resources/repositories/gitea-wtaylor-repositories-old.yaml
- ./resources/repositories/github-wtaylor-repositories.yaml
patches:
- path: ./patches/argocd-cmd-params-cm.yaml
- path: ./patches/argocd-cm.yaml
- path: ./patches/argocd-rbac-cm.yaml
