[project]
name = "device-config"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ansible-lint>=25.4.0",
    "ansible>=11.1.0",
    "hvac>=2.3.0",
]
[tool.uv]
environments = ["platform_system != 'Windows'"]
