helmCharts:
- releaseName: mariadb-operator-crds
  name: mariadb-operator-crds
  repo: https://mariadb-operator.github.io/mariadb-operator
  version: "0.38.1"
  includeCRDs: true
- releaseName: mariadb-operator
  name: mariadb-operator
  repo: https://mariadb-operator.github.io/mariadb-operator
  version: "0.38.1"
  valuesInline:
    extraArgs:
      metrics:
        enabled: false
      webhook:
        cert:
          certManager:
            enabled: true
