helmCharts:
- releaseName: mariadb-operator
  name: mariadb-operator
  repo: https://mariadb-operator.github.io/mariadb-operator
  version: "0.23.1"
  includeCRDs: true
  valuesInline:
    extraArgs:
      metrics:
        enabled: false
      webhook:
        cert:
          certManager:
            enabled: true
