apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app.kubernetes.io/name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:26.0.0
        args:
        - start
        env:
        - name: KC_FEATURES
          value: token-exchange,persistent-user-sessions
        - name: KC_HTTP_ENABLED
          value: 'true'
        - name: KC_HOSTNAME
          value: https://auth.tk831.net
        - name: KC_PROXY_HEADERS
          value: xforwarded
        - name: KC_DB
          value: postgres
        - name: KC_DB_URL_HOST
          value: postgres-tk831-default-rw
        - name: KC_DB_URL_DATABASE
          value: keycloak
        - name: KC_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: keycloak-postgres-credentials
              key: username
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-postgres-credentials
              key: password
        - name: KC_BOOTSTRAP_ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: keycloak-admin-credentials
              key: username
        - name: KC_BOOTSTRAP_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-admin-credentials
              key: password
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        resources:
          requests:
            memory: 512Mi
            cpu: 125m
          limits:
            memory: 1024Mi
            cpu: 512m
