apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/75b325c1be790bc0fc620e3386acfd38365780c7/releases/cnpg-1.26.0-rc2.yaml
