apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dbc-mariadb-default-credentials
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  refreshInterval: 5m
  data:
  - secretKey: root-password
    remoteRef:
      key: kv/services/mariadb/dbc-mariadb-default-credentials
      property: rootPassword
