apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dbc-mariadb-default-temp-s3-credentials
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  refreshInterval: 5m
  data:
  - secretKey: access-key-id
    remoteRef:
      key: kv/services/csi-s3/s3-credentials
      property: access_key
  - secretKey: secret-access-key
    remoteRef:
      key: kv/services/csi-s3/s3-credentials
      property: secret_key
