apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: csi-s3-credentials
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  refreshInterval: 5m
  data:
  - secretKey: access_key
    remoteRef:
      key: kv/services/csi-s3/s3-credentials
      property: access_key
  - secretKey: secret_key
    remoteRef:
      key: kv/services/csi-s3/s3-credentials
      property: secret_key
  target:
    template:
      data:
        endpoint: https://s3.willtaylor.info
        accessKeyID: "{{ .access_key }}"
        secretAccessKey: "{{ .secret_key }}"
