apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: blungebot-cm
  files:
  - files/config.yaml
resources:
- resources/statefulset.yaml
- resources/service-credentials-secret.yaml
