helmCharts:
- releaseName: velero
  name: velero
  repo: https://vmware-tanzu.github.io/helm-charts
  version: "7.1.5"
  includeCRDs: true
  namespace: velero
  valuesInline:
    configuration:
      backupStorageLocation:
      - name: local-only
        provider: aws
        bucket: ssdnb-velero
        default: true
        accessMode: ReadOnly
        credential:
          name: cloud-credentials
          key: cloud
        config:
          region: eu-west-1
          s3ForcePathStyle: "false"
          s3Url: https://s3.willtaylor.info
      - name: full-remote
        provider: aws
        bucket: ssd-velero
        accessMode: ReadOnly
        credential:
          name: cloud-credentials
          key: cloud
        config:
          region: eu-west-1
          s3ForcePathStyle: "false"
          s3Url: https://s3.willtaylor.info
      volumeSnapshotLocation: []
      uploaderType: kopia
      defaultBackupStorageLocation: local-only
      logFormat: text
      defaultVolumesToFsBackup: false
    backupsEnabled: true
    snapshotsEnabled: false
    deployNodeAgent: true
    initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.8.2
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: /target
        name: plugins
    nodeAgent:
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 1
          memory: 4Gi
    extraObjects:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: velero
        labels:
          pod-security.kubernetes.io/audit: privileged
          pod-security.kubernetes.io/enforce: privileged
          pod-security.kubernetes.io/warn: privileged
    - apiVersion: external-secrets.io/v1beta1
      kind: ExternalSecret
      metadata:
        name: cloud-credentials
        namespace: velero
      spec:
        secretStoreRef:
          name: vault
          kind: ClusterSecretStore
        refreshInterval: 5m
        data:
        - secretKey: cloud
          remoteRef:
            key: kv/services/velero/backup-location-s3-credentials
            property: config
resources:
- resources/change-storage-class-cm.yaml
