- name: Install wireguard and tools
  become: true
  apt:
    name:
    - wireguard
    state: present
- name: Enable ipv4 forwarding
  become: true
  lineinfile:
    path: /etc/sysctl.conf
    regexp: net.ipv4.ip_forward
    line: net.ipv4.ip_forward=1
  register: ipv4_forwarding
- name: Enable ipv6 forwarding
  become: true
  lineinfile:
    path: /etc/sysctl.conf
    regexp: net.ipv6.conf.all.forwarding
    line: net.ipv6.conf.all.forwarding=1
  register: ipv6_forwarding
- name: Reload sysctl
  become: true
  command: sysctl -p
  when: ipv4_forwarding.changed or ipv6_forwarding.changed
