apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-credentials
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  refreshInterval: 5m
  data:
  - secretKey: clientSecret
    remoteRef:
      key: kv/services/argocd/keycloak-credentials
      property: clientSecret
  target:
    name: argocd-secret
    creationPolicy: Merge
    deletionPolicy: Merge
    template:
      engineVersion: v2
      data:
        oidc.keycloak.clientSecret: '{{ .clientSecret }}'
