- name: Install ISCSI target utilities
  become: true
  apt:
    state: present
    name: targetcli-fb
- name: Create homelab-democratic-csi user
  become: true
  user:
    name: homelab-democratic-csi
    uid: 1001
    groups:
    - sudo
- name: Create .ssh directory for homelab-democratic-csi user
  become: true
  file:
    state: directory
    path: /home/homelab-democratic-csi/.ssh
    owner: homelab-democratic-csi
    group: homelab-democratic-csi
    mode: '0700'
- name: Add authorized_keys for homelab-democratic-csi user
  become: true
  copy:
    dest: /home/homelab-democratic-csi/.ssh/authorized_keys
    owner: homelab-democratic-csi
    group: homelab-democratic-csi
    mode: '0600'
    content: |
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEq/P75ao2hf3xd4TxoqKOSTIAGsk7QW7Y9LMics7PPd wtaylor@nebuchadnezzar
- name: Remove login banner for homelab-democratic-csi user
  become: true
  file:
    state: touch
    path: /home/homelab-democratic-csi/.hushlogin
    owner: homelab-democratic-csi
    group: homelab-democratic-csi
    mode: '0600'
