apiVersion: v1
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: gitea-ops-repositories
stringData:
  type: git
  url: https://gitea.willtaylor.info/Ops/*
