apiVersion: v1
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: gitea-wtaylor-repositories-tk831
stringData:
  type: git
  url: https://gitea.tk831.net/wtaylor/*
