apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wtaylor-gitea-credentials-tk831
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  refreshInterval: 5m
  data:
  - secretKey: username
    remoteRef:
      key: kv/services/argocd/wtaylor-gitea-credentials
      property: username
  - secretKey: password
    remoteRef:
      key: kv/services/argocd/wtaylor-gitea-credentials
      property: password
  target:
    deletionPolicy: Delete
    template:
      engineVersion: v2
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        type: git
        url: https://gitea.tk831.net/
        username: '{{ .username }}'
        password: '{{ .password }}'
