- hosts: container-services.willtaylor.info
  remote_user: wtaylor
  vars:
    proxy_network: proxy
  roles:
  # - role: ../../common/roles/create-system-users
  #   system_users:
  #   - username: caddy
  #     uid: 2000
  #   - username: vector
  #     uid: 2001
  #   - username: victoria-logs
  #     uid: 2002
  #   - username: victoria-metrics
  #     uid: 2003
  #   - username: grafana
  #     uid: 2004
  #   - username: versitygw
  #     uid: 2005
  # - role: ../../common/roles/prepare-disks
  #   disks:
  #   - serial: viscsi-caddy-data
  #     label: caddy-data
  #     mountpoint: /var/mnt/caddy/data
  #     owner: caddy
  #     mode: "0700"
  #   - serial: viscsi-vl-data
  #     label: victoria-logs-data
  #     mountpoint: /var/mnt/victorialogs/data
  #     owner: victoria-logs
  #     mode: "0700"
  #   - serial: viscsi-vm-data
  #     label: victoria-metrics-data
  #     mountpoint: /var/mnt/victoriametrics/data
  #     owner: victoria-metrics
  #     mode: "0700"
  #   - serial: viscsi-grafana-data
  #     label: grafana-data
  #     mountpoint: /var/mnt/grafana/data
  #     owner: grafana
  #     mode: "0700"
  #   - serial: viscsi-vector-data
  #     label: vector-data
  #     mountpoint: /var/mnt/vector/data
  #     owner: vector
  #     mode: "0700"
  #   - serial: viscsi-vs3-data
  #     label: versitygw-data
  #     fstype: xfs
  #     mountpoint: /var/mnt/versitygw/data
  #     owner: versitygw
  #     mode: "0700"
  - role: ../../common/roles/quadlet-network
    network_name: "{{ proxy_network }}"
  - role: ./roles/quadlet-versitygw
  # - role: ../../common/roles/quadlet-network
  #   network_name: observability-stack
  # - role: ./roles/deploy-victoria-logs
  # - role: ./roles/deploy-victoria-metrics
  # - role: ./roles/deploy-vector-aggregator
  # - role: ./roles/deploy-grafana
  - role: ../../common/roles/quadlet-caddy
    caddy_data_dir: "/var/mnt/caddy/data"
    cloudflare_token: "{{ (lookup('community.hashi_vault.vault_kv2_get', 'system/nas-rp-server/cloudflare-credentials', url=vault_address, engine_mount_point=vault_secret_mount)).secret.api_token }}"
    requires_mounts_for: /var/mnt/caddy/data
    proxy_hosts:
    - domain: s3.tk831.net
      dest: http://versitygw:8080
    - domain: ui.s3.tk831.net
      dest: http://versitygw:8081
