- name: Install dependencies
  apt:
    state: present
    name:
    - debian-keyring
    - debian-archive-keyring
    - apt-transport-https
    - python3-debian
- name: Add repo using key from URL
  deb822_repository:
    name: hashicorp
    types: deb
    uris: https://apt.releases.hashicorp.com
    suites: '{{ ansible_distribution_release }}'
    components: main
    architectures: amd64
    signed_by: https://apt.releases.hashicorp.com/gpg
- name: Install vault
  apt:
    name: vault
