#                                    __   __  __
#                                    \ \ / / / /
#                                     \ V / / /
#                                      \_/  \/
#
#                                    V E C T O R
#                                   Configuration
#
# ------------------------------------------------------------------------------
# Website: https://vector.dev
# Docs: https://vector.dev/docs
# Chat: https://chat.vector.dev
# ------------------------------------------------------------------------------

data_dir: /mnt/vector/data
api:
  enabled: true
  address: 127.0.0.1:8686
  playground: false
schema:
  log_namespace: true
sources:
  internal_metrics:
    type: internal_metrics
  internal_logs:
    type: internal_logs
transforms:
  internal_logs_enriched:
    type: remap
    inputs: [internal_logs]
    source: |-
      .service = "vector"
      .host = get_hostname!()
sinks:
  generic_metrics:
    type: prometheus_remote_write
    inputs: [internal_metrics]
    endpoint: http://metrics-server.willtaylor.info:8428/api/v1/write
    healthcheck:
      enabled: false
  machine_service_logs:
    type: elasticsearch
    inputs: [internal_logs_enriched]
    endpoints: ['http://logs-server.willtaylor.info:9428/insert/elasticsearch']
    mode: bulk
    api_version: v8
    healthcheck:
      enabled: false
    query:
      _msg_field: message
      _time_field: timestamp
      _stream_fields: host,service
