apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-default-barman-s3-credentials
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  refreshInterval: 5m
  data:
  - secretKey: access_key
    remoteRef:
      key: kv/services/postgres/barman-backup-and-wal-s3-archive-credentials
      property: access_key
  - secretKey: secret_key
    remoteRef:
      key: kv/services/postgres/barman-backup-and-wal-s3-archive-credentials
      property: secret_key
