apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-default-admin-credentials
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  refreshInterval: 5m
  data:
  - secretKey: username
    remoteRef:
      key: kv/services/postgres/dbc-postgres-default-credentials
      property: superuserUsername
  - secretKey: password
    remoteRef:
      key: kv/services/postgres/dbc-postgres-default-credentials
      property: superuserPassword
  target:
    deletionPolicy: Delete
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: '{{ .username }}'
        password: '{{ .password }}'
