apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-tk831-default-role-paperless
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  refreshInterval: 5m
  target:
    template:
      type: kubernetes.io/basic-auth
    deletionPolicy: Delete
  data:
  - secretKey: username
    remoteRef:
      key: kv/services/paperless/database-credentials
      property: username
  - secretKey: password
    remoteRef:
      key: kv/services/paperless/database-credentials
      property: password
