apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: proxmox-csi-plugin
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  refreshInterval: 5m
  data:
  - secretKey: apiTokenId
    remoteRef:
      key: kv/services/velero/backup-location-s3-credentials
      property: api_token_id
  - secretKey: apiToken
    remoteRef:
      key: kv/services/velero/backup-location-s3-credentials
      property: api_token
  target:
    template:
      engineVersion: v2
      data:
        config.yaml: |
          clusters:
          - url: https://red-one.willtaylor.info:8006/api2/json
            insecure: true
            token_id: "{{ .apiTokenId }}"
            token_secret: "{{ .apiToken }}"
            region: red-squadron
