apiVersion: v1
kind: Secret
metadata:
  name: vault-auth-vault-longlived-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: vault-auth
type: kubernetes.io/service-account-token
