apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: blungebot-service-credentials
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  refreshInterval: 5m
  target:
    deletionPolicy: Delete
  data:
  - secretKey: telegramToken
    remoteRef:
      key: kv/services/blungebot/telegram-credentials
      property: token
  - secretKey: mumbleUsername
    remoteRef:
      key: kv/services/blungebot/mumble-credentials
      property: username
  - secretKey: mumblePassword
    remoteRef:
      key: kv/services/blungebot/mumble-credentials
      property: password
