apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-data-pvc
  labels:
    app.kubernetes.io/name: gitea
spec:
  storageClassName: proxmox-zfs
  volumeName: pvc-e2d4abfd-ae77-4f48-922b-dc8eb5ee8e44
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-git-pvc
  labels:
    app.kubernetes.io/name: gitea
spec:
  storageClassName: proxmox-zfs
  volumeName: pvc-451cc0d3-a702-4974-b6ee-0453d5658cc0
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-ssh-pvc
  labels:
    app.kubernetes.io/name: gitea
spec:
  storageClassName: proxmox-zfs
  volumeName: pvc-b9680f8e-248a-4fee-a0ee-6309c368bbda
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
