apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-data-pvc
  labels:
    app.kubernetes.io/name: gitea
spec:
  storageClassName: proxmox-zfs
  volumeName: pvc-4542f48d-6569-45a5-a684-820fb5a1684d
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-git-pvc
  labels:
    app.kubernetes.io/name: gitea
spec:
  storageClassName: proxmox-zfs
  volumeName: pvc-7a07e30d-147a-4acc-94a2-7a3fb20a6e69
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-ssh-pvc
  labels:
    app.kubernetes.io/name: gitea
spec:
  storageClassName: proxmox-zfs
  volumeName: pvc-c1dd4f6a-8166-4469-b6b3-40bd81559060
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
