apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-data-pvc
  labels:
    app.kubernetes.io/name: gitea
spec:
  storageClassName: proxmox-zfs
  volumeName: pvc-a11e756d-2946-4615-b340-209464f1ef2e
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-git-pvc
  labels:
    app.kubernetes.io/name: gitea
spec:
  storageClassName: proxmox-zfs
  volumeName: pvc-9b6ed77b-608f-487c-b5f6-3e4b911aee71
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-ssh-pvc
  labels:
    app.kubernetes.io/name: gitea
spec:
  storageClassName: proxmox-zfs
  volumeName: pvc-cef4dac2-a844-481d-aa74-bcaec1e41f8d
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
