apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gitea
spec:
  parentRefs:
  - name: default
  hostnames: [gitea.tk831.net]
  rules:
  - matches:
    - path:
        type: Prefix
        value: /
    backendRefs:
    - name: gitea-http
      port: 3000
