apiVersion: v1
kind: Service
metadata:
  name: gitea-http
  labels:
    app.kubernetes.io/name: gitea
spec:
  selector:
    app.kubernetes.io/name: gitea
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: gitea-git
  labels:
    app.kubernetes.io/name: gitea
spec:
  selector:
    app.kubernetes.io/name: gitea
  ports:
  - name: ssh
    port: 3539
    targetPort: 3539
  type: LoadBalancer
  loadBalancerIP: "172.28.5.1"
