apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-git-pvc-volsync-restic-config
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  refreshInterval: 60m
  target:
    template:
      type: kubernetes.io/Opaque
      data:
        RESTIC_REPOSITORY: s3:https://s3.willtaylor.info/ssd-backup-volsync/gitea-git-pvc
        RESTIC_PASSWORD: "{{ .restic_password }}"
        AWS_ACCESS_KEY_ID: "{{ .access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ .secret_key }}"
    deletionPolicy: Delete
  data:
  - secretKey: access_key
    remoteRef:
      key: kv/services/volsync/s3-credentials
      property: access_key
  - secretKey: secret_key
    remoteRef:
      key: kv/services/volsync/s3-credentials
      property: secret_key
  - secretKey: restic_password
    remoteRef:
      key: kv/services/volsync/restic-credentials
      property: password
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-git-pvc
  labels:
    app.kubernetes.io/name: gitea
spec:
  storageClassName: proxmox-zfs
  volumeName: pvc-9b6ed77b-608f-487c-b5f6-3e4b911aee71
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: gitea-git-pvc
spec:
  sourcePVC: gitea-git-pvc
  trigger:
    # Take a backup every night at 4am
    schedule: "37 8 * * *"
  restic:
    copyMethod: Direct
    pruneIntervalDays: 7
    repository: gitea-git-pvc-volsync-restic-config
    retain:
      hourly: 1
      daily: 7
      weekly: 2
      monthly: 2
      yearly: 0
