helmCharts:
- releaseName: cert-manager
  name: cert-manager
  repo: https://charts.jetstack.io
  includeCRDs: true
  version: v1.12.3
  namespace: cert-manager
  valuesInline:
    installCRDs: true
    extraArgs:
    - --dns01-recursive-nameservers-only
    - --dns01-recursive-nameservers=1.1.1.1:53,8.8.8.8:53
resources:
- resources/cloudflare-credentials.yaml
- resources/cluster-issuer.yaml
