helmCharts:
- releaseName: cert-manager
  name: cert-manager
  repo: https://charts.jetstack.io
  includeCRDs: true
  version: v1.17.2
  namespace: cert-manager
  valuesInline:
    crds:
      enabled: true
    dns01RecursiveNameserversOnly: true
    dns01RecursiveNameservers: '1.1.1.1:53,8.8.8.8:53'
resources:
- resources/cloudflare-credentials.yaml
- resources/cluster-issuer.yaml
