apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: blunge
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  description: Applications to enrich the lives of blun.ge
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
