- name: Install dependent apt packages
  become: true
  apt:
    state: present
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
- name: Install docker apt-key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add docker repository
  become: true
  apt_repository:
    state: present
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
- name: Install docker engine
  become: true
  apt:
    update_cache: true
    state: present
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin
    - docker-compose
    - python3-docker
- name: Write ubuntu docker configuration file
  become: true
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0640'
  register: docker_config
- name: Start and enable docker
  become: true
  systemd:
    daemon_reload: true
    name: docker
    state: "{{ 'reloaded' if docker_config.changed else 'started' }}"
    enabled: true
