- hosts: external-insight
  remote_user: root
  roles:
  - role: ../../../../common/roles/update-system
  - role: ../../../../common/roles/install-docker
  - role: ../../../../common/roles/wireguard-client
    vars:
      autostart: true
      interface:
        privateKey: "{{ (lookup('community.hashi_vault.vault_kv2_get', 'services/wireguard/keys', url=vault_address, engine_mount_point=vault_secret_mount)).secret['external-insight'].privateKey }}"
        address: "172.28.4.10/24"
        post_up: resolvectl dns %i 172.28.4.1; resolvectl domain %i ~willtaylor.info
      peers:
      - publicKey: "{{ (lookup('community.hashi_vault.vault_kv2_get', 'services/wireguard/server-public-key', url=vault_address, engine_mount_point=vault_secret_mount)).secret.publicKey }}"
        allowedIps: "192.168.0.0/16,172.28.0.0/16"
        endpoint: wireguard.willtaylor.info:51820
  - role: roles/uptime-kuma
  - role: ../../../../common/roles/servers/reverse-proxy
    vars:
      cloudflare_token: "{{ (lookup('community.hashi_vault.vault_kv2_get', 'system/nas-rp-server/cloudflare-credentials', url=vault_address, engine_mount_point=vault_secret_mount)).secret.api_token }}"
      proxy_hosts:
      - domain: status.willtaylor.info
        dest: http://localhost:3001
  - role: ../../../../common/roles/servers/vector-agent
    vars:
      tls:
        ca_pem: "{{ (lookup('community.hashi_vault.vault_kv2_get', 'services/vector/external-insight/tls-certificate', url=vault_address, engine_mount_point=vault_secret_mount)).secret.caChain }}"
        cert_crt: "{{ (lookup('community.hashi_vault.vault_kv2_get', 'services/vector/external-insight/tls-certificate', url=vault_address, engine_mount_point=vault_secret_mount)).secret.certificate }}"
        cert_key: "{{ (lookup('community.hashi_vault.vault_kv2_get', 'services/vector/external-insight/tls-certificate', url=vault_address, engine_mount_point=vault_secret_mount)).secret.privateKey }}"
      vector_config:
        data_dir: /var/lib/vector
        sources:
          vector_logs:
            type: "internal_logs"
          host_metrics:
            type: host_metrics
            collectors:
            - cgroups
            - cpu
            - disk
            - filesystem
            - load
            - host
            - memory
            - network
            filesystem:
              devices:
                includes: ["sda", "vda", "vdb"]
              mountpoints:
                includes: ["/", "/mnt/data"]
          internal_metrics:
            type: internal_metrics
          journald:
            type: journald
            include_units:
            - caddy.service
            include_matches:
              CONTAINER_NAME: ["uptime_kuma_uptime_kuma_1"]
          uptime_kuma_pm_scrape:
            type: prometheus_scrape
            endpoints: ["http://localhost:3001/metrics"]
            scrape_interval_secs: 30
            auth:
              strategy: basic
              user: "{{ (lookup('community.hashi_vault.vault_kv2_get', 'services/vector/external-insight/uptime-kuma-basic-auth-credentials', url=vault_address, engine_mount_point=vault_secret_mount)).secret.username }}"
              password: "{{ (lookup('community.hashi_vault.vault_kv2_get', 'services/vector/external-insight/uptime-kuma-basic-auth-credentials', url=vault_address, engine_mount_point=vault_secret_mount)).secret.password }}"
        sinks:
          console:
            type: console
            inputs: ["vector_logs"]
            encoding:
              codec: text
          vector_aggregator:
            type: vector
            inputs: ["host_metrics", "internal_metrics", "journald", "uptime_kuma_pm_scrape"]
            address: https://vector-aggregator.willtaylor.info:6000
            version: "2"
            tls:
              enabled: true
              ca_file: /etc/vector/tls/ca.pem
              crt_file: /etc/vector/tls/cert.crt
              key_file: /etc/vector/tls/cert.key
              verify_certificate: true
              verify_hostname: false
