#                                    __   __  __
#                                    \ \ / / / /
#                                     \ V / / /
#                                      \_/  \/
#
#                                    V E C T O R
#                                   Configuration
#
# ------------------------------------------------------------------------------
# Website: https://vector.dev
# Docs: https://vector.dev/docs
# Chat: https://chat.vector.dev
# ------------------------------------------------------------------------------

data_dir: /mnt/vector/data
api:
  enabled: true
  address: 127.0.0.1:8686
  playground: false
schema:
  log_namespace: true
sources:
  vector_internal_metrics:
    type: internal_metrics
  vector_internal_logs:
    type: internal_logs
  vector_upstream:
    type: vector
    address: 0.0.0.0:6000
    version: "2"
    tls:
      enabled: false
  prometheus_remote_write:
    type: prometheus_remote_write
    address: 0.0.0.0:9090
  syslog:
    type: syslog
    address: 0.0.0.0:1468
    mode: tcp
  talos_kernel_logs:
    address: 0.0.0.0:6050
    type: socket
    mode: udp
    max_length: 102400
    decoding:
      codec: json
    host_key: __host
  talos_service_logs:
    address: 0.0.0.0:6051
    type: socket
    mode: udp
    max_length: 102400
    decoding:
      codec: json
    host_key: __host
    # prometheus_scrape:
    #   type: prometheus_scrape
    #   endpoints:
    #   - https://opnsense.willtaylor.info:9100/metrics
    #   scrape_interval_secs: 15
    #   instance_tag: instance
    #   endpoint_tag: endpoint
transforms:
  vl_vector_internal_logs:
    type: remap
    inputs: [vector_internal_logs]
    source: |-
      .service = "vector"
      .host = get_hostname!()

      %vl.msg_field = "message"
      %vl.time_field = "timestamp"
      %vl.stream_fields = "host,service"
  vl_talos_kernel_logs:
    type: remap
    inputs: [talos_kernel_logs]
    source: |-
      %vl.msg_field = "msg"
      %vl.time_field = "talos-time"
      %vl.stream_fields = "facility"
  vl_talos_service_logs:
    type: remap
    inputs: [talos_service_logs]
    source: |-
      %vl.msg_field = "msg"
      %vl.time_field = "talos-time"
      %vl.stream_fields = "talos-service"
sinks:
  generic_metrics:
    type: prometheus_remote_write
    inputs:
    - vector_internal_metrics
    - vector_upstream
    # - prometheus_scrape
    - prometheus_remote_write
    endpoint: http://metrics-server.willtaylor.info:8428/api/v1/write
    healthcheck:
      enabled: false
  generic_logs:
    type: elasticsearch
    inputs:
    - vl_vector_internal_logs
    - vl_talos_kernel_logs
    - vl_talos_service_logs
    endpoints: ['http://logs-server.willtaylor.info:9428/insert/elasticsearch']
    mode: bulk
    api_version: v8
    healthcheck:
      enabled: false
    query:
      _msg_field: "{{ %vl.msg_field }}"
      _time_field: "{{ %vl.time_field }}"
      _stream_fields: "{{ %vl.stream_fields }}"
